import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-introduction',
  templateUrl: './introduction.component.html',
  styleUrls: ['./introduction.component.scss']
})
export class IntroductionComponent implements OnInit {

  gridRequestObj = `{
  "entity": {},      // any data that can be sent from outside the grid component
  "filters": [],     // filters array generated by the grid
  "page": 1,         // page no
  "perPage": 100,    // page size
  "sort": null,      // sort -> asc/desc/null
  "sortField": null  // field name to sort data
}`;

  gridResponseObj = `{
  "payload": {
    "gridData": [...],   // grid data
    "totalCount": 1000,  // total count of records in the database for pagination purposes
    "other": null        // send any other data you wish here in order to use in your application, Refer to @Output() responseEmit: EventEmitter <GridResponse>. 
  },
  "success": true,      // if this value is not returned the grid will not populate the data, handle errors if false
  "message": "SUCCESS"  // show error message if success is false
}`;

  constructor() { }

  ngOnInit(): void {
  }


}
